; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
framework = espidf
monitor_speed = 115200
upload_speed = 921600

[env:cyd1]
board = jczn_2432s028r
build_flags = -DNODEA
upload_port = /dev/ttyUSB1

[env:cyd2]
board = jczn_2432s028r
build_flags = -DNODEB
upload_port = /dev/ttyUSB2

[env:esp32c6]
board = esp32-c6-devkitc-1
build_flags = -DNODEB
lib_deps =  
	h2zero/esp-nimble-cpp
board_build.partitions = huge_app.csv
upload_port = /dev/ttyUSB2